
// Bank's Date format

// Date number of times
exports.ICICIBANKFORMATCOUNT = 15;
exports.KOTAKBANKFORMATCOUNT = 15;
exports.CITIBANKFORMATCOUNT = 15;
exports.ORIENTALBANKFORMATCOUNT = 15;
exports.KARURAVYSYABANKFORMATCOUNT = 15;
exports.UBIBANKFORMATCOUNT = 15;             // United Bank of India
exports.HDFCBANKFORMATCOUNT = 30;
exports.IDBIBANKFORMATCOUNT = 15;
exports.BOBBANKFORMATCOUNT = 15;
exports.SBIBANKFORMATCOUNT = 30;
exports.INDUSLANDBANKFORMATCOUNT = 15;
exports.INDIANOVERSEASBANKFORMATCOUNT = 15;
